---
name: Henry
surname: Cho
position: "Senior Analyst - Data Analytics, Reporting and Evaluation"
#address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 778 999 6639
#www: mariecurie.com
email: henry.cho@outlook.com
#twitter: mariecurie
#github: mariecurie
linkedin: linkedin.com/in/henrycho/
date: "`r format(Sys.time(), '%B %Y')`"
docname:  Coded and written in R
output: vitae::awesomecv
---


```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```
\
\
Board Search Committee \
C/O Joan Kluge \
1220 Homer Street \
Vancouver, BC \
Canada V6B 2Y5 \
\
\
**Re: Board Member - Compassionate Eye Foundation**
\
Dear Joan Kluge,\
\
I am writing to express my interest in joining the Board at the Compassionate Eye Foundation. I want to join Compassionate Eye because I want to change lives and contribute to something larger than myself. \
\
Although I am lacking in board experience, I believe that I can bring value to the organization in other ways. I am highly analytical and have over 6 years of experience working in analytics and data science, most recently in the health care industry. In my current role at the Provincial Health Services Authority (PHSA), I am directly supporting the roll out of the provincial vaccination efforts through the development of tools which monitor and inform decisions at a strategic level. Additionally, during the onset of the pandemic, I developed a tool to directly keep track of the hospitalized Covid patients, as well as patient occupancy and equipment use. The numbers from the tool at the time I am writing this are still being reported to the minister of health herself. \
\
In addition to my analytical skillset, I believe I am also able to bring a strong business perspective to the organization as well. I am also currently pursuing my MBA and am expected to graduate by the end of the year. I believe that the value of a business perspective cannot be understated. From a financial standpoint, I would be able to provide an assessment on whether financial risk is being managed effectively and whether they align with the long-term strategic goals of the organization. I would also be able to bring in a business planning approach from a budgeting perspective to help inform strategic decisions.\
\
Additionally, in my undergraduate studies I specialized in marketing and entrepreneurship.
I believe that I would be able to bring additional value to the organization through my breadth of business knowledge whether it is through the lens of marketing, finance, business operations or analytics. \
\
I have attached my resume for your review and would welcome the opportunity to meet you and discuss further. \
\
\
Sincerely,\
\
Henry Cho
